target 'Segment-Apptimize_Example' do
  pod 'Segment-Apptimize', :path => '../'

  target 'Segment-Apptimize_Tests' do
    inherit! :search_paths

    pod 'OCMockito'
    pod 'Specta'
    pod 'Expecta'
  end
end
